# Bold container-specific starship configuration
format = """
[🐳](fg:black bold) \
[CONTAINER](bg:bright-cyan fg:black bold) \
$directory\
$git_branch\
$git_status\
$python\
$fill\
$character"""

[directory]
style = "bg:blue fg:bright-white bold"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[git_branch]
format = "[ $symbol$branch ]($style)"
style = "bg:purple fg:bright-white bold"

[git_status]
format = "[ $all_status$ahead_behind ]($style)"
style = "bg:purple fg:bright-white bold"

[python]
format = "[ ${symbol}v${version} ]($style)"
style = "bg:green fg:black bold"

[fill]
symbol = " "